output: partb_1 partb_2 partb_3

partb_1: partb_1.c 
	 gcc -o partb_1 partb_1.c -lpthread

partb_2: partb_2.c 
	 gcc -o partb_2 partb_2.c -lpthread

partb_3: partb_3.c 
	 gcc -o partb_3 partb_3.c -lpthread


clean: 
	rm * .o output
